import math

BITS = 16
MAX_VAL = (1 << BITS) - 1
COLS = 9

def quantize(x):
    return round(x * MAX_VAL)

tab = [quantize(math.sin(t / 180.0 * math.pi)) for t in range(0, 90)]

print("// Generated by misc/gen-fixed-sin.py")
print("uint16_t fixedSinTab[] = {")
for base in range(0, len(tab), COLS):
    print("\t" + "".join("0x%04x," % v for v in tab[base:base+COLS]))
print("};")
